name: Build and Push

inputs:
  target:
    required: true
    type: string
  tag:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Build
      shell: bash
      run: |
        docker build . -t ghcr.io/${{github.repository_owner}}/${{inputs.target}}:${{inputs.tag}} --file ${{inputs.target}}.Dockerfile

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}

    - name: Push by tag name
      shell: bash
      run: |
        docker push ghcr.io/${{github.repository_owner}}/${{inputs.target}}:${{inputs.tag}}

    - name: Push by latest
      shell: bash
      run: |
        docker image tag ghcr.io/${{github.repository_owner}}/${{inputs.target}}:${{inputs.tag}} ghcr.io/${{github.repository_owner}}/${{inputs.target}}:latest
        docker push ghcr.io/${{github.repository_owner}}/${{inputs.target}}:latest
